local awful = require("awful")
awful.spawn.with_shell('xrdb -merge ~/.Xresources')
awful.spawn.with_shell('mpDris2 &')
awful.spawn.with_shell('picom &')
awful.spawn.with_shell('udiskie &')
awful.spawn.with_shell('xss-lock lock &')
