#!/bin/sh

USER="dark-Jedi2108"
TOKEN="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"

notifications=$(echo "user = \"$USER:$TOKEN\"" | curl -sf -K- https://api.github.com/notifications | jq ".[].unread" | grep -c true)

if [ "$notifications" -gt 0 ]; then
    echo "# $notifications"
else
    echo "0"
fi
