#!/usr/bin/bash

is_active=$(pgrep redshift)

toggle() {
    if [[ -n $is_active ]]; then
        pkill redshift
    else
        redshift &
    fi
}


class() {
    if [[ -n $is_active ]]; then
        echo active
    else
        echo inactive
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--class" ]]; then
    class
fi