#!/usr/bin/sh
toggle(){
    if [[ ! `pidof picom` ]]; then
        picom --experimental-backends &
    else 
        pkill -9 picom
    fi
}

class(){
    if [[ ! `pidof picom` ]]; then
        echo inactive
    else 
        echo active
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--class" ]]; then
    class
fi
