#!/bin/bash

PLAYERCTL_STATUS=$(playerctl --player=spotify status 2>/dev/null)
EXIT_CODE=$?
if [[ $EXIT_CODE -eq 0 ]]; then
    STATUS=$PLAYERCTL_STATUS
    icon="󰏥"
    if [[ $STATUS == "Paused" ]]; then
      icon="󰐌"
    fi
    SONG_NAME=$(playerctl --player=spotify metadata title 2>/dev/null)
    ARTIST_NAME=$(playerctl --player=spotify metadata artist 2>/dev/null)
    ARTIST_NAME="by $ARTIST_NAME"
    SHUFFLE=$(playerctl --player=spotify shuffle)
    LOOP=$(playerctl --player=spotify loop)
else
    STATUS=""
    SONG_NAME="Spotify Not Found"
    ARTIST_NAME="Open Spotify First"
    icon="󰐌"
fi


if [[ $1 == "--status" ]]; then
    echo $STATUS
elif [[ $1 == "--song" ]]; then
  count=$(echo -n "$SONG_NAME" | wc -c)
  if [ "$count" -le 17 ]; then
		echo $SONG_NAME
	else 
		echo ${SONG_NAME:0:17}...
	fi
elif [[ $1 == "--artist" ]]; then
    echo "$ARTIST_NAME"
elif [[ $1 == "--image" ]]; then
    echo $IMAGE
elif [[ $1 == "--icon" ]]; then
    echo $icon
elif [[ $1 == "--loop" ]]; then
    echo $LOOP
elif [[ $1 == "--shuf" ]]; then
    echo $SHUFFLE
fi
