#!/usr/bin/sh
toggle(){
    if [[ ! `pidof tint2` ]]; then
        tint2 &
    else 
        pkill -9 tint2
    fi
}

class(){
    if [[ ! `pidof picom` ]]; then
        echo inactive
    else 
        echo active
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--class" ]]; then
    class
fi
