#!/usr/bin/bash

is_active=$(pidof redshift)

toggle() {
    if [[ -n $is_active ]]; then
        pkill redshift
    else
        redshift &
    fi
}

status() {
    if [[ -n $is_active ]]; then
        echo "Turned on"
        exit 1
    else
        echo "Turned off"
        exit 1
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--status" ]]; then
    status
fi
