#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
udiskie &
$HOME/.local/bin/eww daemon &
$HOME/.fehbg &
$HOME/.config/polybar/launch.sh &
picom --experimental-backends &
dunst &
bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
